version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: benco
      POSTGRES_PASSWORD: loco
      POSTGRES_DB: root_jdr_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data